services:
  # Django web application
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    # Keep native DATABASE_* variables for consistency with entrypoint.sh
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/media
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  # PostgreSQL database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

# Persistent data volumes
volumes:
  postgres_data: # Database data
  static_volume: # Django static files
  media_volume: # Django uploaded media
