# Generated by Django 5.2 on 2025-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max Temperature')),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Min Temperature')),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precipitation')),
                ('windspeed_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max Windspeed')),
                ('uv_index_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max UV Index')),
                ('sunshine_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sunshine Hours')),
                ('sundown_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sundown Hours')),
                ('weather_code', models.IntegerField(verbose_name='Weather Code')),
            ],
            options={
                'db_table': 'weather_data',
                'ordering': ['province', 'time'],
                'managed': False,
            },
        ),
    ]
