# Generated by Django 5.2 on 2025-05-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dwpt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rhum', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wpgt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tsun', models.IntegerField(blank=True, null=True)),
                ('wdir', models.IntegerField(blank=True, null=True)),
                ('coco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'weather_data',
                'ordering': ['location', 'date'],
                'managed': False,
            },
        ),
    ]
