# Generated by Django 5.2 on 2025-05-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max Temperature')),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Min Temperature')),
                ('weather_code', models.IntegerField(verbose_name='Weather Code')),
                ('weather_description', models.CharField(max_length=100, verbose_name='Weather_Description')),
            ],
            options={
                'db_table': 'predict_weather',
                'ordering': ['province', 'date'],
                'managed': False,
            },
        ),
    ]
