# Generated by Django 4.2.7 on 2025-05-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'managed': False, 'ordering': ['province', 'time']},
        ),
    ]
