# Generated by Django 5.2 on 2025-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictweather',
            options={'managed': False, 'ordering': ['province', 'time']},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
