# Generated by Django 5.2 on 2025-05-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_subscriber_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('email', 'province')},
        ),
    ]
